image: docker-reg.devops.xiaohongshu.com/fe/fe-ci:$FE_CI_IMAGE_LATEST

before_script:
  - node -v
  - formula -V
  - lerna bootstrap

stages:
  - test
  - deploy

test:
  stage: test
  script:
    # - formula lint
    - formula test

deploy:production:
  stage: deploy
  script:
    - lerna run build
    - lerna publish
  only:
    - /^v\d+\.\d+\.\d+$/

deploy:prerelease:
  stage: deploy
  script:
    - lerna publish --tag=prerelease
  only:
    - /^v\d+\.\d+\.\d+-\d+$/

deploy:alpha:
  stage: deploy
  script:
    - lerna run build
    - lerna publish
  only:
    - /^v\d+\.\d+\.\d+-alpha\./