image: docker-reg.devops.xiaohongshu.com/fe/fe-ci:$FE_CI_IMAGE_LATEST

variables:
  REMOTES: "static01,static02"
  BROWSER_OUTOUT_FOLDER: "./public"
  REMOTES_FOLDER: "/data/formula-static/$CI_PROJECT_NAME"

before_script:
  - node -v
  - formula -V
  - lerna bootstrap
  - echo $CI_COMMIT_TAG
  - export PKGLEFT=${CI_COMMIT_TAG%@*}
  - export PKGNAME=${PKGLEFT/@xhs\/}
  - export PKGVERSION=${CI_COMMIT_TAG##*@}
  - echo $PKGNAME

stages:
  - test
  - deploy

# test:
#   stage: test
#   script:
#     - formula lint -p
#     - npm run type-check
#   cache:
#     untracked: true
#     paths:
#       - node_modules/

deploy:
  stage: deploy
  script:
    - cd packages/$PKGNAME
    - npm run build
    - npm publish
  only:
    - tags